"use client";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "./components/Navbar";


export default function RootLayout({ children }) {
    return (
        <AuthProvider>
        <html lang="en">
        <head>
            <title>RECIPEDIA</title>
            <meta name="description" content="Generated by sso" />
            <link rel="icon" href="/favicon.ico" />
        </head>
        <body className="font-sans bg-gray-100 text-gray-900 flex flex-col min-h-screen">
        {/* Header */}
        <header className="bg-gray-800 text-white py-4 shadow-md fixed w-full top-0 left-0 z-10">
            <Navbar></Navbar>
        </header>

        {/* Main Content */}
        <main className="flex-grow max-w-7xl mx-auto px-4 sm:px-2 md:px-4 py-6 mt-16">
            {children}
        </main>

        {/* Footer */}
        <footer className="bg-gray-800 text-white py-4 text-center">
            <p>&copy; 2025 Recipedia. All rights reserved.</p>
        </footer>
        </body>
        </html>
        </AuthProvider>
    );
}
