import "./globals.css";
import Link from "next/link";


export const metadata = {
  title: "RECIPEDIA",
  description: "Generated by sso",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
    <header>
        <nav>
            <ul>
                <li><Link href="/">Home</Link></li>
                <li><Link href="/recipe">Recipe</Link></li>
            </ul>
        </nav>
    </header>
    <main>
        {children}
    </main>
    <footer>
        <p>&copy; 2025 Recipedia. All rights reserved.</p>
    </footer>
    </body>
    </html>
  );
}
